# Generated by Django 5.1.6 on 2025-03-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='game',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='game_photos/'),
        ),
    ]
