# Generated by Django 5.1.6 on 2025-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_photo_url_game_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='photo',
        ),
        migrations.AddField(
            model_name='game',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
